In [20]:
from sqlalchemy import create_engine
import psycopg2
import pandas as pd

from config import db_password

In [21]:
db_string = f"postgresql://postgres:{db_password}@127.0.0.1:5432/acc_data"

In [22]:
engine = create_engine(db_string)

In [23]:
df = pd.read_csv("Resources/Austin_Animal_Center_Intakes.csv")
df

,Animal ID,Name,DateTime,MonthYear,Found Location,Intake Type,Intake Condition,Animal Type,Sex upon Intake,Age upon Intake,Breed,Color
0,A786884,*Brock,01/03/2019 04:19:00 PM,01/03/2019 04:19:00 PM,2501 Magin Meadow Dr in Austin (TX),Stray,Normal,Dog,Neutered Male,2 years,Beagle Mix,Tricolor
1,A706918,Belle,07/05/2015 12:59:00 PM,07/05/2015 12:59:00 PM,9409 Bluegrass Dr in Austin (TX),Stray,Normal,Dog,Spayed Female,8 years,English Springer Spaniel,White/Liver
2,A724273,Runster,04/14/2016 06:43:00 PM,04/14/2016 06:43:00 PM,2818 Palomino Trail in Austin (TX),Stray,Normal,Dog,Intact Male,11 months,Basenji Mix,Sable/White
3,A665644,NaN,10/21/2013 07:59:00 AM,10/21/2013 07:59:00 AM,Austin (TX),Stray,Sick,Cat,Intact Female,4 weeks,Domestic Shorthair Mix,Calico
4,A682524,Rio,06/29/2014 10:38:00 AM,06/29/2014 10:38:00 AM,800 Grove Blvd in Austin (TX),Stray,Normal,Dog,Neutered Male,4 years,Doberman Pinsch/Australian Cattle Dog,Tan/Gray
...,...,...,...,...,...,...,...,...,...,...,...,...
135703,A850185,NaN,01/19/2022 05:40:00 PM,01/19/2022 05:40:00 PM,13318 Elm Grove Road in Mustang Ridge (TX),Stray,Normal,Dog,Intact Female,2 years,Labrador Retriever,Cream
135704,A849503,Indigo,01/19/2022 05:10:00 PM,01/19/2022 05:10:00 PM,Austin (TX),Owner Surrender,Normal,Dog,Spayed Female,2 months,Siberian Husky/German Shepherd,Brown
135705,A850189,NaN,01/19/2022 05:40:00 PM,01/19/2022 05:40:00 PM,13318 Elm Grove Road in Mustang Ridge (TX),Stray,Normal,Dog,Unknown,3 days,Labrador Retriever,Cream
135706,A850191,NaN,01/19/2022 05:40:00 PM,01/19/2022 05:40:00 PM,13318 Elm Grove Road in Mustang Ridge (TX),Stray,Normal,Dog,Unknown,3 days,Labrador Retriever,Cream
135707,A850186,NaN,01/19/2022 05:40:00 PM,01/19/2022 05:40:00 PM,13318 Elm Grove Road in Mustang Ridge (TX),Stray,Normal,Dog,Unknown,3 days,Labrador Retriever,Cream

In [26]:
df = pd.read_csv("Resources/Austin_Animal_Center_Intakes.csv")
df.to_sql(name='intakes', con=engine)

In [27]:
df = pd.read_csv("Resources/Austin_Animal_Center_Outcomes.csv")
df

,Animal ID,Name,DateTime,MonthYear,Date of Birth,Outcome Type,Outcome Subtype,Animal Type,Sex upon Outcome,Age upon Outcome,Breed,Color
0,A794011,Chunk,05/08/2019 06:20:00 PM,05/08/2019 06:20:00 PM,05/02/2017,Rto-Adopt,NaN,Cat,Neutered Male,2 years,Domestic Shorthair Mix,Brown Tabby/White
1,A776359,Gizmo,07/18/2018 04:02:00 PM,07/18/2018 04:02:00 PM,07/12/2017,Adoption,NaN,Dog,Neutered Male,1 year,Chihuahua Shorthair Mix,White/Brown
2,A821648,NaN,08/16/2020 11:38:00 AM,08/16/2020 11:38:00 AM,08/16/2019,Euthanasia,NaN,Other,Unknown,1 year,Raccoon,Gray
3,A720371,Moose,02/13/2016 05:59:00 PM,02/13/2016 05:59:00 PM,10/08/2015,Adoption,NaN,Dog,Neutered Male,4 months,Anatol Shepherd/Labrador Retriever,Buff
4,A674754,NaN,03/18/2014 11:47:00 AM,03/18/2014 11:47:00 AM,03/12/2014,Transfer,Partner,Cat,Intact Male,6 days,Domestic Shorthair Mix,Orange Tabby
...,...,...,...,...,...,...,...,...,...,...,...,...
135969,A849858,NaN,01/19/2022 05:45:00 PM,01/19/2022 05:45:00 PM,07/14/2021,Adoption,NaN,Cat,Spayed Female,6 months,Domestic Shorthair,White/Black
135970,A850191,NaN,01/19/2022 05:47:00 PM,01/19/2022 05:47:00 PM,01/16/2022,NaN,NaN,Dog,Unknown,NaN,Labrador Retriever,Cream
135971,A850187,NaN,01/19/2022 05:45:00 PM,01/19/2022 05:45:00 PM,01/16/2022,NaN,NaN,Dog,Unknown,NaN,Labrador Retriever,Cream
135972,A849645,NaN,01/19/2022 05:37:00 PM,01/19/2022 05:37:00 PM,11/04/2021,Adoption,NaN,Cat,Intact Male,2 months,Domestic Shorthair,Black
135973,A849786,A849786,01/19/2022 05:19:00 PM,01/19/2022 05:19:00 PM,01/13/2020,Adoption,NaN,Cat,Spayed Female,2 years,Domestic Medium Hair Mix,Brown Tabby

In [28]:
df = pd.read_csv("Resources/Austin_Animal_Center_Outcomes.csv")
df.to_sql(name='outcomes', con=engine)

In [29]:
df = pd.read_csv("Resources/merged_AKC.csv")
df

,Unnamed: 0,Animal ID,Name,Found Location,Intake Type,Intake Condition,Breed,Color,Age_in_Years,Intactness,...,Drop,Sorted_Color,Length_of_Stay,Breed_update,Breed1,Breed2,AKC_group1,Size1,AKC_group2,Size2
0,0,A006100,Scamp,8700 Research in Austin (TX),Public Assist,Normal,Spinone Italiano Mix,Yellow/White,6.000000,Neutered,...,No,Tricolor,2,Spinone Italiano,Spinone Italiano,NaN,sporting,large,NaN,NaN
1,1,A006100,Scamp,8700 Research Blvd in Austin (TX),Public Assist,Normal,Spinone Italiano Mix,Yellow/White,7.000000,Neutered,...,No,Liver/White,2,Spinone Italiano,Spinone Italiano,NaN,sporting,large,NaN,NaN
2,2,A006100,Scamp,Colony Creek And Hunters Trace in Austin (TX),Stray,Normal,Spinone Italiano Mix,Yellow/White,10.000000,Neutered,...,No,Sable/White,1,Spinone Italiano,Spinone Italiano,NaN,sporting,large,NaN,NaN
3,3,A047759,Oreo,Austin (TX),Owner Surrender,Normal,Dachshund,Tricolor,10.000000,Neutered,...,No,Gray/Tan,6,Dachshund,Dachshund,NaN,hound,small,NaN,NaN
4,4,A134067,Bandit,12034 Research Blvd in Austin (TX),Public Assist,Injured,Shetland Sheepdog,Brown/White,16.000000,Neutered,...,No,Chocolate,1,Shetland Sheepdog,Shetland Sheepdog,NaN,herding,small,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
75986,75986,A850187,NaN,13318 Elm Grove Road in Mustang Ridge (TX),Stray,Normal,Labrador Retriever,Cream,0.008219,Unknown,...,No,Black/Brown,1,Labrador Retriever,Labrador Retriever,NaN,sporting,medium,NaN,NaN
75987,75987,A850188,NaN,13318 Elm Grove Road in Mustang Ridge (TX),Stray,Normal,Labrador Retriever,Cream,0.008219,Unknown,...,No,Tan,1,Labrador Retriever,Labrador Retriever,NaN,sporting,medium,NaN,NaN
75988,75988,A850189,NaN,13318 Elm Grove Road in Mustang Ridge (TX),Stray,Normal,Labrador Retriever,Cream,0.008219,Unknown,...,No,Yellow,1,Labrador Retriever,Labrador Retriever,NaN,sporting,medium,NaN,NaN
75989,75989,A850190,NaN,13318 Elm Grove Road in Mustang Ridge (TX),Stray,Normal,Labrador Retriever,Cream,0.008219,Unknown,...,No,Black/White,1,Labrador Retriever,Labrador Retriever,NaN,sporting,medium,NaN,NaN
75990,75990,A850191,NaN,13318 Elm Grove Road in Mustang Ridge (TX),Stray,Normal,Labrador Retriever,Cream,0.008219,Unknown,...,No,Black/White,1,Labrador Retriever,Labrador Retriever,NaN,sporting,medium,NaN,NaN

In [31]:
df = pd.read_csv("Resources/merged_AKC.csv")
df.to_sql(name='merged_AKC', con=engine)

In [32]:
df = pd.read_csv("Resources/BreedInfo.csv")
df

,Breed,Austin_breedname,AKC_group,size_cat
0,Affenpinscher,Affenpinscher,toy,small
1,Afghan Hound,Afghan Hound,hound,large
2,Airedale Terrier,Airedale Terrier,terrier,medium
3,Akita,Akita,working,large
4,Alaskan Eskimo Dog,Klee Klai,non-sporting,small
...,...,...,...,...
232,Spanish Mastiff,Spanish Mastiff,working,large
233,Spanish Water Dog,Spanish Water Dog,herding,medium
234,Grand Basset Griffon Vendeen,Grand Basset Griffon Vendeen,hound,medium
235,Alaskan Klee Kai,Alaskan Klee Kai,working,medium
236,Hovawart,Hovawart,working,large

In [33]:
df = pd.read_csv("Resources/Austin_Animal_Center_Outcomes.csv")
df.to_sql(name='breedinfo', con=engine)